name: cleanpro
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.8
  firebase_core: ^2.27.0
  firebase_database: ^10.4.9
  flutter:
    sdk: flutter
  google_fonts: 6.1.0
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/img/
