// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyfE2NE3LJqiIUXE6V-2DUuulRGpgdm3M',
    appId: '1:230578105535:web:a03b57e101f4833dac2a0a',
    messagingSenderId: '230578105535',
    projectId: 'esp32-interruptor',
    authDomain: 'esp32-interruptor.firebaseapp.com',
    databaseURL: 'https://esp32-interruptor-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-interruptor.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2nUUx665OWuwmvus1tN2ywFL2h69JO5E',
    appId: '1:230578105535:android:a6545a9ceaf37ec9ac2a0a',
    messagingSenderId: '230578105535',
    projectId: 'esp32-interruptor',
    databaseURL: 'https://esp32-interruptor-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-interruptor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAboh9tjKCV17imqlgLCbVaGESLsAal2-Q',
    appId: '1:230578105535:ios:701bfec2f379a9ffac2a0a',
    messagingSenderId: '230578105535',
    projectId: 'esp32-interruptor',
    databaseURL: 'https://esp32-interruptor-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-interruptor.appspot.com',
    iosBundleId: 'com.example.cleanpro',
  );
}
